# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ipyfernel',
                'doc_host': 'https://drscotthawley.github.io',
                'git_url': 'https://github.com/drscotthawley/ipyfernel',
                'lib_path': 'ipyfernel'},
  'syms': { 'ipyfernel.core': { 'ipyfernel.core.foo': ('core.html#foo', 'ipyfernel/core.py'),
                                'ipyfernel.core.local': ('core.html#local', 'ipyfernel/core.py'),
                                'ipyfernel.core.set_ssh_config': ('core.html#set_ssh_config', 'ipyfernel/core.py')}}}
